project:
  type: book
  output-dir: _book

book:
  title: "Threatened ecosystems of Myanmar"
  subtitle: "An IUCN Red List of Ecosystems Assessment"
  author: 
    - name: "Norah Jones"
    - name: "John Doe"
  date: "9/18/2025"
  chapters:
    - index.qmd
    - 01_foreword.qmd
    - 02_preface.qmd
    - 03_acknowledgments.qmd
    - coordinating-orgs.qmd
    - summary.qmd
    - intro.qmd
    - ecosystem_overview.qmd
    - assessments/overview.qmd
    - part: "Ecosystem Assessments"
      chapters:
        - assessments/tanintharyi_island_rainforest.qmd
        - assessments/tanintharyi_sundaic_lowland_evergreen_forest.qmd
    - assessment_outcomes.qmd
    - recommendations.qmd
    - references.qmd
  appendices:
    - appendix_1.qmd

crossref:
  appendix-title: "App."
  appendix-delim: ":"

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true
