project:
  type: book
  output-dir: _book

book:
  title: "Threatend ecosystems of Myanmar"
  subtitle: "An IUCN Red List of Ecosystems Assessment"
  author: 
    - name: "Norah Jones"
    - name: "John Doe"
  date: "9/18/2025"
  chapters:
    - index.qmd
    - foreword.qmd
    - preface.qmd
    - acknowledgments.qmd
    - coordinating-orgs.qmd
    - summary.qmd
    - intro.qmd
    - ecosystem_overview.qmd
    - assessments/overview.qmd
    - part: "Ecosystem Assessments"
      chapters:
        - assessments/tanintharyi_island_rainforest.qmd
        - assessments/tanintharyi_sundaic_lowland_evergreen_forest.qmd
    - assessment_outcomes.qmd
    - recommendations.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true
