project:
  type: book
  output-dir: _book

book:
  title: "Threatened ecosystems of Myanmar"
  subtitle: "An IUCN Red List of Ecosystems Assessment"
  author: 
    - name: "Norah Jones"
    - name: "John Doe"
  date: "9/18/2025"
  chapters:
    - index.qmd
    - 0.1_foreword.qmd
    - 0.2_preface.qmd
    - 0.3_acknowledgments.qmd
    - 0.4_coordinating-orgs.qmd
    - 0.5_summary.qmd
    - 1_intro.qmd
    - ecosystem_overview.qmd
    - assessments/overview.qmd
    - part: "Ecosystem Assessments"
      chapters:
        - assessments/tanintharyi_island_rainforest.qmd
        - assessments/tanintharyi_sundaic_lowland_evergreen_forest.qmd
    - assessment_outcomes.qmd
    - recommendations.qmd
    - references.qmd
  appendices:
    - appendix_1.qmd

crossref:
  appendix-title: "App."
  appendix-delim: ":"

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true
