ecosystem_name: "Tropical forest"
country_name: "Wakanda"
authors:
  - "J. Smith"
  - "J. Pérez"
ecosystem_names_local:
  - name: "Ecosystem Name 1"
    reference: "@bibtexReference1"
  - name: "Ecosystem Name 2"
    reference: "@bibtexReference2"
biome: Tropical and subtropical forests (T1)
functional_group: T1.1
global_classification: MMR-TSAMPLE
iucn_status: Endangered
ecosystem_photo: images/MMR-TSAMPLE_photo.png
# ecosystem_photo: null
ecosystem_map: images/MMR-TSAMPLE_map.png
# ecosystem_map: null
ecosystem_image:
  asset_id: projects/goog-rle-assessments/assets/mm_ecosys_v7b
  pixel_value: 53
description: >
  The ecosystem description goes here.
distribution: >
  The ecosystem distribution text goes here.
characteristic_native_biota: >
  The ecosystem's characteristic native biota text goes here.
abiotic_environment: >
  The ecosystem's abiotic environment text goes here.
key_processes_and_interactions: >
  The ecosystem's key processes and interactions text goes here.
major_threats: >
  The ecosystem's major threats text goes here.
ecosystem_collapse_definition: >
  The ecosystem's ecosystem collapse definition text goes here.
assessment_summary: >
  The ecosystem's assessment summary text goes here.
criteria_status:
  A:
    A1: NE
    A2a: NE
    A2b: NE
    A3: NE
  B:
    B1: NE
    B2: NE
    subcriteria: [subcriteria1, subcriteria2, ...]
    B3: NE
  C:
    C1: NE
    C2a: NE
    C2b: NE
    C3: NE
  D:
    D1: NE
    D2a: NE
    D2b: NE
    D3: NE
  E:
    E: NE
assessment_outcome: >
  The ecosystem's assessment outcome text goes here.
year_published: 1999
date_assessed: 24th January 2000
assessment_credits:
  assessed_by: Jane Smith
  reviewed_by: Jose Pérez
  contributions_by: Kevin Bacon
criterion_a_description: >
  The ecosystem's criterion A description text goes here.
criterion_b_description:
  text: The ecosystem's criterion B description text goes here.
criterion_c_description: >
  The ecosystem's criterion C description text goes here.
criterion_d_description: >
  The ecosystem's criterion D description text goes here.
criterion_e_description: >
  The ecosystem's criterion E description text goes here.
