country_name: Myanmar
# ISO 3166-1 alpha-2 code for the country
# See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
country_code: MM
gee_project_path: "projects/goog-rle-assessments/assets/"
classified_image:
  asset_id: mm_ecosys_v7b
  classes:
    - id: 52
      name: Tanintharyi island rainforest
      code: MMR-T1.1.1
    - id: 54
      name: Tanintharyi Sundaic lowland evergreen rainforest
      code: MMR-T1.1.2
    - id: 53
      name: Tanintharyi limestone tropical evergreen forest
      code: MMR-T1.1.3
    # - id: 55
    #   name: Tanintharyi upland evergreen rainforest
    #   code: MMR-T1.1.4
    # - id: 49
    #   name: Kayin evergreen tropical rainforest
    #   code: MMR-T1.1.5
    # - id: 51
    #   name: Southern Rakhine evergreen rainforest
    #   code: MMR-T1.1.6
    # - id: 50
    #   name: Western Shan Plateau subtropical evergreen rainforest
    #   code: MMR-T1.1.7
    # - id: 66
    #   name: Kachin-Sagaing low elevation evergreen subtropical rainforest
    #   code: MMR-T1.1.8
    # - id: 48
    #   name: Kachin-Sagaing mid elevation subtropical rainforest
    #   code: MMR-T1.1.9
    # - id: 57
    #   name: Kachin Hills subtropical rainforest
    #   code: MMR-T1.1.10
    # - id: 38
    #   name: Tanintharyi semi-evergreen forest
    #   code: MMR-T1.2.1
    # - id: 58
    #   name: Rocky Taninthayri karst
    #   code: MMR-T1.2.2
    # - id: 56
    #   name: Mixed cane break
    #   code: MMR-T1.2.3
    # - id: 37
    #   name: Bago semi-evergreen forest
    #   code: MMR-T1.2.4
    # - id: 45
    #   name: Dry zone foothills spiny scrub
    #   code: MMR-T1.2.5
    # - id: 44
    #   name: Rakhine Elephant Range bamboo brake
    #   code: MMR-T1.2.6
    # - id: 39
    #   name: Elephant range semi-evergreen dry forest
    #   code: MMR-T1.2.7
    # - id: 40
    #   name: Magway dry cycad forest
    #   code: MMR-T1.2.8
    # - id: 41
    #   name: Magway semi-evergreen dry gully forest
    #   code: MMR-T1.2.9
    # - id: 36
    #   name: East Myanmar dry valley forest
    #   code: MMR-T1.2.10
    # - id: 47
    #   name: Eastern Shan semi-evergreen forest
    #   code: MMR-T1.2.11
    # - id: 43
    #   name: Western Shan semi-evergreen forest
    #   code: MMR-T1.2.12
    # - id: 42
    #   name: Indaing forest
    #   code: MMR-T1.2.13
    # - id: 65
    #   name: Northern semi-evergreen forest
    #   code: MMR-T1.2.14
    # - id: 61
    #   name: Tanintharyi cloud forest
    #   code: MMR-T1.3.1
    # - id: 2
    #   name: Kachin mountain conifer forest
    #   code: MMR-T2.1.1
    # - id: 33
    #   name: Kachin montane temperate broadleaf forest
    #   code: MMR-T2.4.6
    # - id: 64
    #   name: Shan warm temperate rainforest
    #   code: MMR-T2.4.1
    # - id: 62
    #   name: Chin Hills warm temperate rainforest
    #   code: MMR-T2.4.2
    # - id: 59
    #   name: Sagaing warm temperate rainforest
    #   code: MMR-T2.4.3
    # - id: 63
    #   name: Kachin warm temperate rainforest
    #   code: MMR-T2.4.4
    # - id: 7
    #   name: Mountain bamboo brake
    #   code: MMR-T2.4.5
    # - id: 35
    #   name: Rakhine coastal savanna
    #   code: MMR-T4.2.1
    # - id: 17
    #   name: Central Ayeyarwady Than-Dahat grassy forest
    #   code: MMR-T4.2.2
    # - id: 20
    #   name: Central Ayerawady Palm savanna
    #   code: MMR-T4.2.3
    # - id: 19
    #   name: Shwe Settaw Sha-Bamboo thicket
    #   code: MMR-T4.2.4
    # - id: 18
    #   name: Magway Than-Dahat dry grassy forest
    #   code: MMR-T4.2.5
    # - id: 25
    #   name: Sha thorny scrub
    #   code: MMR-T4.2.6
    # - id: 16
    #   name: Shan foothills Than-Dahat grassy forest
    #   code: MMR-T4.2.7
    # - id: 24
    #   name: Shan hills pine savanna
    #   code: MMR-T4.2.8
    # - id: 21
    #   name: Chin hills pine savanna
    #   code: MMR-T4.2.9
    # - id: 23
    #   name: Sagaing hills pine savanna
    #   code: MMR-T4.2.10
    # - id: 22
    #   name: Kachin pine savanna
    #   code: MMR-T4.2.11
    # - id: 3
    #   name: Shan plateau grasslands
    #   code: MMR-T4.5.1
    # - id: 15
    #   name: Kachin snowfields
    #   code: MMR-T6.1.1
    # - id: 14
    #   name: Alpine cliffs and screes
    #   code: MMR-T6.2.1
    # - id: 32
    #   name: High mountain scrub
    #   code: MMR-T6.4.1
    # - id: 31
    #   name: Alpine herbfield
    #   code: MMR-T6.4.2
    # - id: 1
    #   name: Aerobic Karst caves
    #   code: MMR-S1.1.1
    # - id: 34
    #   name: Ayeyarwady kanazo swamp forest
    #   code: MMR-TF1.1.1
    # - id: 30
    #   name: Central dry evergreen riparian forest
    #   code: MMR-TF1.1.2
    # - id: 29
    #   name: Mixed delta scrub
    #   code: MMR-TF1.1.3
    # - id: 28
    #   name: Ayeyarwady floodplain wetlands
    #   code: MMR-TF1.4.1
    # - id: 27
    #   name: Central Ayeyarwady floodplain grasslands
    #   code: MMR-TF1.4.2
    # - id: 6
    #   name: Glacial lakes
    #   code: MMR-F2.4.1
    # - id: 13
    #   name: Coastal mudflats
    #   code: MMR-MT1.2.1
    # - id: 26
    #   name: Sandy shoreline
    #   code: MMR-MT1.3.1
    # - id: 4
    #   name: Tanintharyi coastal dune forest
    #   code: MMR-MT2.1.1
    # - id: 5
    #   name: Rakhine coastal dune forest
    #   code: MMR-MT2.1.2
    # - id: 11
    #   name: Tanintharyi mangrove forest
    #   code: MMR-MFT1.2.1
    # - id: 8
    #   name: Ayeyarwady delta mangrove forest
    #   code: MMR-MFT1.2.2
    # - id: 9
    #   name: Dwarf mangrove (shrubland) on shingle
    #   code: MMR-MFT1.2.3
    # - id: 10
    #   name: Rakhine mangrove forest on mud
    #   code: MMR-MFT1.2.4
    # - id: 12
    #   name: Grassy saltmarsh
    #   code: MMR-MFT1.3.1
